package com.yoncent.model;

import com.yoncent.model.base.BaseMainMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MainMenu extends BaseMainMenu<MainMenu> {
	public static final MainMenu dao = new MainMenu();
}
